Websites/Ruby_on_rails/friends/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  resources :friends
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "home/about"
  # Defines the root path route ("/")
  root "home#index"
end

Websites/Ruby_on_rails/friends/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

Websites/Ruby_on_rails/friends/app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
end

Websites/Ruby_on_rails/friends/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :friends
end

Websites/Ruby_on_rails/friends/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Websites/Ruby_on_rails/friends/app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: [:show, :edit, :update, :destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    #@friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = current_user.friends.build(friend_params)
    #@friend = Friend.new
    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not Authorized To Edit This Friend" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

Websites/Ruby_on_rails/friends/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
    @about_me = "My Name is John Elder"
  end 
end

Websites/Ruby_on_rails/friends/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def after_sign_up_path_for(resource)
    root_path # or any other path
  end
end

Websites/Ruby_on_rails/friends/app/helpers/application_helper.rb
module ApplicationHelper
end

Websites/Ruby_on_rails/friends/app/helpers/friends_helper.rb
module FriendsHelper
end

Websites/Ruby_on_rails/friends/app/views/friends/_form.html.erb
<style>
  .form-setting {
      width: 60vw;
      margin-left: auto;
      margin-right: auto;
  }
</style>

<%= form_with(model: friend, local: true) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group form-setting">
    <% form.label :first_name %>
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>

  <div class="field form-group form-setting">
    <% form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
  </div>

  <div class="field form-group form-setting">
    <% form.label :email, style: "display: block" %>
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
  </div>

  <div class="field form-group form-setting">
    <% form.label :phone, style: "display: block" %>
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone Number" %>
  </div>

  <div class="field form-group form-setting">
    <% form.label :twitter, style: "display: block" %>
    <%= form.text_field :twitter, class:"form-control", placeholder:"Twitter" %>
  </div>
  <div class="field form-group form-setting">
    <% form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id, id: :friend_user_id, class:"form-control", value: current_user.id, type: :hidden %>
  </div>

  <br>
  <div class="actions">
    <%= form.submit class:'btn btn-secondary' %>
  </div>
<% end %>

Websites/Ruby_on_rails/friends/app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>First name:</strong>
    <%= friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= friend.twitter %>
  </p>

</div>

Websites/Ruby_on_rails/friends/app/views/friends/edit.html.erb
<div class="card">
  <div class="card-header">
    <h1>Editing friend</h1>
  </div>
  <div class="card-body">
    <%= render "form", friend: @friend %>
  </div>
</div>

<br>

<div>
  <%= link_to "Show", @friend, class:"btn btn-secondary"%> |
  <%= link_to "Back", friends_path, class:"btn btn-dark" %>
</div>

Websites/Ruby_on_rails/friends/app/views/friends/index.html.erb
<style>
  .table-setting {
      background-color: #00008b;
  }
</style>

<h1>Friend List</h1>
<br>
<table class="table table-striped table-bordered">
  <thead class="table-dark table-setting">
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Twitter</th>
      <!--<th>User Id</th>-->
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @friends.each do |friend| %>
      <% if friend.user == current_user %>
        <tr>
          <td><%= friend.first_name %></td>
          <td><%= friend.last_name %></td>
          <td><%= friend.email %></td>
          <td><%= friend.phone %></td>
          <td><%= friend.twitter %></td>
          <!--<td></td>-->
          <td><%= link_to "Show", friend, class:"btn btn-outline-info btn-sm" %></td>
          <td><%= link_to "Edit", edit_friend_path(friend), class:"btn btn-outline-secondary btn-sm" %></td>
          <td><%= link_to "Delete", friend, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger btn-sm" %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "New friend", new_friend_path, class:"btn btn-secondary" %>

Websites/Ruby_on_rails/friends/app/views/friends/new.html.erb
<div class="card" style="width: 80vw;margin-left:auto;margin-right:auto">
  <div class="card-header">
    <h1>New friend</h1>
  </div>
  <div class="card-body">
    <%= render "form", friend: @friend %>
  </div>
</div>

<br>

<div>
  <%= link_to "Back", friends_path %>
</div>

<br>

Websites/Ruby_on_rails/friends/app/views/friends/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">
    <%= @friend.first_name + " " + @friend.last_name %>
  </h1>
  <p class="lead">
    <%= @friend.first_name %>   |
    <%= @friend.email %>   |
    <%= @friend.twitter %>
  </p>
  <div>
  <%= link_to "Edit", edit_friend_path(@friend), class:"btn btn-secondary" %>
  </div>
</div>

<%= button_to "Destroy this friend", @friend, method: :delete, class:"btn btn-danger" %>
<br>
<%= link_to "Back", friends_path %>

Websites/Ruby_on_rails/friends/app/views/home/_header.html.erb
<style>
    .navbar-default {
        background-color: #00008b;
    }
</style>

<nav class="navbar navbar-expand-lg navbar-default navbar-dark">
  <%= link_to "Home", root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "About Website", home_about_path, class:"nav-link" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Friends", friends_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Add Friend", new_friend_path, class:"nav-link" %>
        </li>
      <% end %>
      <% if user_signed_in? == false %>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path , class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign in", new_user_session_path, class:"nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>
        <li class="nav-item">
          <%= link_to "Edit profile", edit_user_registration_path, class:"nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

Websites/Ruby_on_rails/friends/app/views/home/about.html.erb
<div class="card">
  <div class="card-header">
    <h1>About Website</h1>
  </div>
  <div class="card-body">
    <h5 class="card-title">Are you having trouble remembering your friends' information? Then this
    is the website just for You! Sign Up and save your friends' data at one place!</h5>
    <p class="card-text">Please follow the next crucial steps before
      using this website. The first step is to make sure that you have at least one friend. If this
    is apparently not the case for you, please seek immediate socializing. The second step is to push that beautifully well constructed, limited edition, pixel rich, blue button down below.</p>

    <button type="button" class="btn btn-primary">Useless button</button>
  </div>
</div>

Websites/Ruby_on_rails/friends/app/views/home/index.html.erb
<style>
    .carousel-inner {
        display: flex;
        align-content: center;
        max-height: 250px !important;
    }

    .carousel-item {
        margin-left: auto;
        margin-right: auto;
        width: auto;
        height: 250px;
    }

    .settings-image {
        height: 250px;
    }
</style>

<div class="jumbotron" style="border-radius: 25px">
  <h1 class="display-4">Hello Ruby On Rails <img src="https://cdn-icons-png.flaticon.com/128/5821/5821932.png" alt="Hand-waving icon" height="100px"></h1>

  <p class="lead">This is my first <a href="https://rubyonrails.org/">Ruby On Rails</a> project where I became
    familiar with the concept and basics of <a href="https://getbootstrap.com/">Bootstrap</a> too. This website was made
  with the help and instructions of a <a href="https://www.youtube.com/c/Freecodecamp" target="_blank">freeCodeCamp.org</a> Youtube
    <a href="https://www.youtube.com/watch?v=fmyvWz5TUWg&t=7148s" target="_blank">video</a>. I made this to learn and explore this amazing programming language and
  to prepare for the apprenticeship.</p>

  <hr class="my-4">

  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="d-block w-100 settings-image" src="https://upload.wikimedia.org/wikipedia/commons/1/16/Ruby_on_Rails-logo.png" alt="First slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100 settings-image" src="https://res.cloudinary.com/practicaldev/image/fetch/s--jvDLhx0b--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/i/cpcr5w0kgl6j94tss7n9.png" alt="Second slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100 settings-image" src="https://res.cloudinary.com/practicaldev/image/fetch/s--jvDLhx0b--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/i/cpcr5w0kgl6j94tss7n9.png" alt="Third slide">
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

</div>

Websites/Ruby_on_rails/friends/app/views/layouts/_alerts.html.erb
<div class="alert alert-primary alert-dismissible fade show" role="alert">

  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

Websites/Ruby_on_rails/friends/app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="icon" href="https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Ruby_logo.svg/640px-Ruby_logo.svg.png">
    <title>Friends Management</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render "home/header" %>

    <div class="container" style="text-align:center;min-height: 550px;
      overflow: hidden;">
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <br>
      <%= yield %>
    </div>

    <div class="container-fluid"></div>

    <footer class="bg-light text-center text-lg-start">
      <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        © 2022 Copyright:
        <a class="text-dark" href="https://github.com/AndrasTarlos">itguy</a>
      </div>
    </footer>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    -->
  </body>
</html>